### PR TITLE
Hash long filenames 

### LINKED ISSUE #303: Filenames exceed the ext4 max-length of 255
**Describe the bug**
The algorithm that generates the filename that the transformer must write out can generate filenames longer than 255 characters if the input dataset name/filename is too long. This happens for some CMS datasets.

**To Reproduce**
1. Transform files from the CMS dataset using the following transform
```python
with sx.ignore_cache():
    sx_dataset = sx.ServiceXDataset(dataset_name, "uproot", max_workers=5)
    src = ServiceXSourceUpROOT(sx_dataset, "Events")
    data = src.Select("lambda e: {'Muon_pt': e['Muon_pt'], 'Electron_pt': e['Electron_pt']}") \
        .AsAwkwardArray('junk.ak') \
        .value()
```

You'll get back the following error from ServiceX:
```
-> error: Failed to transform input file root://cmsdcadisk.fnal.gov:1094//dcache/uscmsdisk/store/mc/RunIIFall17NanoAODv7/DYJetsToLL_Pt-250To400_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/PU2017_12Apr2018_Nano02Apr2020_102X_mc2017_realistic_v8-v1/60000/455A3019-BAF1-5943-8405-4989A2E080D9.root: [Errno 36] Failed to open local file '/home/output/root:::cmsdcadisk.fnal.gov:1094::dcache:uscmsdisk:store:mc:RunIIFall17NanoAODv7:DYJetsToLL_Pt-250To400_TuneCP5_13TeV-amcatnloFXFX-pythia8:NANOAODSIM:PU2017_12Apr2018_Nano02Apr2020_102X_mc2017_realistic_v8-v1:60000:455A3019-BAF1-5943-8405-4989A2E080D9.root.parquet'. Detail: [errno 36] File name too long
```

**Expected behavior**
No crash, baby!

**Additional Context**
This error was first described on [Slack](https://iris-hep.slack.com/archives/CJH870SR2/p1621880146024200) by Burt Holzman, running on the Nebraska coffea-casa cluster.

### PR DESCRIPTION
**Pull request by holzman**
Following @gordonwatts  suggestion to fix https://github.com/ssl-hep/ServiceX/issues/303, this PR replaces long filenames (where their full path would exceed MAX_PATH_LEN=255), with a truncated name with a hash appended.

### CODE REVIEW

**Review by BenGalewsky — CHANGES_REQUESTED** [review]
This is a great idea, but I'd like this PR to do just the one thing, hash long output filenames. Could remove the other fixes? Some of them are obsolete once we merge #24 - the changes from atlas user are welcome, but should be in a separate PR

**Comment by holzman** [comment]
I don't see why this couldn't be split up.

**Comment by gordonwatts** [comment]
Thanks!!

**Comment by holzman** [comment]
Done (with the caveat that I can't test in my environment without the other changes).

**Comment by BenGalewsky** [comment]
Closed via #26

**Pull request closed without merging**
